version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release

platform:
  - Win32

cache:
  - 'c:\choco\ -> appveyor.yml'

install:
  - cinst cppcheck --cache-location=c:\choco\ --version 1.86 --limitoutput -y
  - cinst doxygen.install --cache-location=c:\choco\ --version 1.8.14.20181217 --limitoutput -y

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
