version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64
  - MinGW

cache:
  - '%TEMP%\chocolatey\ -> appveyor.yml'

install:
  - cinst cppcheck --version 1.86 --limitoutput -y
  - cinst doxygen.install --version 1.8.14.20181217 --limitoutput -y

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
